version: "3.8"

services:
  api:
    image: 192.168.56.101:5000/simple-api:1.0
    networks:
      - overlay_internal
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  frontend:
    image: nginx:alpine
    ports:
      - "80:80" # published on host via routing mesh (ingress)
    networks:
      - overlay_external
      - overlay_internal
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
    deploy:
      replicas: 2

networks:
  overlay_internal:
    external: true
  overlay_external:
    external: true

configs:
  nginx_conf:
    file: ./nginx.conf
